
version: '3'

services:

  elasticsearch:
    container_name: "elasticsearch"
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  redis:
    image: redis
    ports:
      - 6379:6379




